[package]
name = "spl-math"
version = "0.3.0"
description = "Solana Program Library Math"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
uint = "0.10"

[dev-dependencies]
proptest = "1.6.0"
libm = "0.2.11"
solana-program-test = "2.2"
solana-transaction = "2.2"
solana-pubkey = "2.2"
solana-signer = "2.2"
solana-keypair = "2.2"
anchor-lang = "0.31"
anchor-spl = "0.31"
# required for solana program test
tokio = { version = "1.43", features = ["rt"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
